jdbc.driverClassName=org.h2.Driver
jdbc.url=jdbc:h2:~/geoportal-harvester-war
jdbc.username=${HRV_JDBC_USER:}
jdbc.password=${HRV_JDBC_PASSWORD:}

geometry.service.url=https://utility.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer

sink.attempt.count=5
sink.attempt.delay=1000

jdbc.script.enabled=false

csw.profiles.folder=

tika.sizeLimit=-1

# Security configuration properties for geoportal-harvester-war
# Use placeholder syntax so environment variables can override these values.
# Example: set HRV_ISSUER to override security.issuer value.

# Authorization Server issuer URL (can be overridden by env var SECURITY_ISSUER)
security.issuer=${HRV_ISSUER:http://localhost:9000}

# Enable OpenID Connect support (true/false) - can be overridden by HRV_ENABLE_OIDC
security.enableOidc=${HRV_ENABLE_OIDC:true}

# UI (Catalog) client - public client (no client secret)- DO NOT CHNAGE THE DEFAULT CLIENT ID 
security.ui.clientId=${HRV_UI_CLIENTID:harvester-ui-client}
security.ui.redirectUri=${HRV_UI_REDIRECTURI:http://localhost:8080/geoportal-harvester-war/callback-popup.html}

# ArcGIS Portal client (Configure below, to use ArcGIS Portal as the Authentication provider for Harvester UI)
# To enable ArcGIS authentication, set HRV_ARCGIS_AUTH_ENABLED to true and provide the clientId, clientSecret, authorizationURI, tokenURI, userInfoURI and userNameAttr values.
security.arcgis.auth.enabled=${HRV_ARCGIS_AUTH_ENABLED:false} 
security.arcgis.clientId=${HRV_ARCGIS_CLIENTID:}
security.arcgis.clientSecret=${HRV_ARCGIS_CLIENTSECRET:}
security.arcgis.authorizationURI=${HRV_ARCGIS_AUTHORIZATIONURI:}
security.arcgis.tokenURI=${HRV_ARCGIS_TOKENURI:}
security.arcgis.userInfoURI=${HRV_ARCGIS_USERINFOURI:}
security.arcgis.userNameAttr=${HRV_ARCGIS_USERINAMEATTR:username}

# Admin API client (confidential)
security.api.admin.clientId=${HRV_API_ADMIN_CLIENTID:}

# Keep bcrypt prefix if you store a BCrypt-hashed secret. Override with HRV_API_ADMIN_CLIENTSECRET
security.api.admin.clientSecret=${HRV_API_ADMIN_CLIENTSECRET:}

# Read-only API client (confidential)
security.api.read.clientId=${HRV_API_READ_CLIENTID:}

# Keep bcrypt prefix if you store a BCrypt-hashed secret. Override with HRV_API_READ_CLIENTSECRET
security.api.read.clientSecret=${HRV_API_READ_CLIENTSECRET:}

# Define public and secured endpoints

#Public endpoints to load Catalog (no authentication required) DO NOT REMOVE THE FIRST LINE BELOW
# if application context is changed, make sure to update the path /geoportal-harvester-war accordingly
security.public-endpoints=/index.html, /login.html,/custom-login.html,/login, /oauth2/**, /callback-popup.html, /login/oauth2/**, /error, /hrv/**, /rest/harvester/security/arcgis-config,/logout
                        
#.roles permitAll or authenticated or  ROLE_ADMIN | ROLE_PUBLISHER | ROLE_USER can be given as comma separated values
# For client_credential scopes use  SCOPE_api.read | SCOPE_api.write
#.method GET | POST | PUT | DELETE can be given as comma separated values

#/rest/harvester/metadata/ - the metadata catalog
security.secured-endpoints[0].pattern=/rest/harvester/brokers/**
security.secured-endpoints[0].roles=SCOPE_api.write,SCOPE_write,ROLE_ADMIN

security.secured-endpoints[1].pattern=/rest/harvester/connectors/**
security.secured-endpoints[1].roles=SCOPE_api.write,SCOPE_write,ROLE_ADMIN

security.secured-endpoints[2].pattern=/rest/harvester/filters/**
security.secured-endpoints[2].roles=SCOPE_api.write,SCOPE_write,ROLE_ADMIN

security.secured-endpoints[3].pattern=/rest/harvester/tasks/**
security.secured-endpoints[3].roles=SCOPE_api.write,SCOPE_write,ROLE_ADMIN

security.secured-endpoints[4].pattern=/rest/harvester/processes/**
security.secured-endpoints[4].roles=SCOPE_api.write,SCOPE_write,ROLE_ADMIN

security.secured-endpoints[5].pattern=/rest/harvester/transformers/**
security.secured-endpoints[5].roles=SCOPE_api.write,SCOPE_write,ROLE_ADMIN

security.secured-endpoints[6].pattern=/rest/harvester/triggers/**
security.secured-endpoints[6].roles=SCOPE_api.write,SCOPE_write,ROLE_ADMIN